### ISSUE TITLE
can't install here what i got:

### ISSUE THREAD

**Issue by Tenebre551** [TencentARC/ColorFlow#6]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.83k/4.83k [00:00<00:00, 1.86MB/s]
latest_net_E.pth: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.0M/12.0M [00:02<00:00, 5.36MB/s]
latest_net_enc.pth: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.4M/17.4M [00:03<00:00, 4.51MB/s]
(…)2manga/color2manga_cycle_ganstft/opt.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.18k/3.18k [00:00<00:00, 1.56MB/s]
image_encoder/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560/560 [00:00<00:00, 218kB/s]
latest_net_G_INTSCR2RGB.pth: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51.9M/51.9M [00:25<00:00, 2.01MB/s]
latest_net_G_RGB2INTSCR.pth: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50.7M/50.7M [00:24<00:00, 2.04MB/s]
latest_net_dec.pth: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.8M/52.8M [00:38<00:00, 1.39MB/s]
sketch/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 572/572 [00:00<00:00, 216kB/s]
unet_lora.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 95.9M/95.9M [01:06<00:00, 1.44MB/s]
MultiResNetModel.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 340M/340M [01:55<00:00, 2.94MB/s]
erika.pth: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 173M/173M [03:24<00:00, 845kB/s]
MultiResNetModel.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 340M/340M [04:04<00:00, 1.39MB/s]
transformer_lora.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442M/442M [05:18<00:00, 1.39MB/s]
diffusion_pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.01G/1.01G [07:49<00:00, 2.15MB/s]
diffusion_pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.37G/3.37G [14:56<00:00, 3.76MB/s]
model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.53G/2.53G [15:01<00:00, 2.81MB/s]
pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.53G/2.53G [14:42<00:00, 2.86MB/s]
Fetching 21 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [15:10<00:00, 43.34s/it]
./colorflow/models--TencentARC--ColorFlow\snapshots\33678ecf09383ea86eb3dc2a35da9dc52e72b482                                                                                                            | 975M/2.53G [08:19<12:55, 2.00MB/s]
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 2.45G/2.53G [14:49<00:17, 4.33MB/s]
  File "app.py", line 82, in <module>██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.53G/2.53G [15:01<00:00, 6.60MB/s]
    line_model.cuda()0%|██████████████████████████████████████████████████████████████████████▍                                                                                                        | 1.02G/2.53G [07:59<07:47, 3.23MB/s]
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda███████████████████████████████████████████████████████████████████████████████████████▎      | 2.43G/2.53G [14:28<00:24, 3.95MB/s]
    return self._apply(lambda t: t.cuda(device))███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 2.49G/2.53G [14:39<00:09, 4.70MB/s]
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply███████████████████████████████████████████████████████████████████████████████████████████▉| 2.53G/2.53G [14:42<00:00, 8.45MB/s]
    module._apply(fn)
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "D:\SOFT\Miniconda\envs\colorflow\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(colorflow) F:\AI\Color_Flow\ColorFlow

**Comment by Macflylegamer** [comment]
Same...

**Comment by Macflylegamer** [comment]
Try that : "pip uninstall torch torchvision torchaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
" it worked for me

**Comment by Macflylegamer** [comment]
Did this work for you?

**Comment by pillowsign** [comment]
Had same issue

> Try that : "pip uninstall torch torchvision torchaudio pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 " it worked for me

Worked for me. Thank you!

**Comment by Daemonhellz** [comment]
> Try that : "pip uninstall torch torchvision torchaudio pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 " it worked for me

This reinstall of pytorch components allows to bypass the error `AssertionError("Torch not compiled with CUDA enabled")`

However, is this project only compatible with Nvidia GPUs?
Trying to launch the app afterwards threw the following error : `RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

Indeed, I don't have a Nvidia GPU/drivers

**Comment by Ihateyoudattebayo** [comment]
> > Try that : "pip uninstall torch torchvision torchaudio pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 " it worked for me
> 
> This reinstall of pytorch components allows to bypass the error `AssertionError("Torch not compiled with CUDA enabled")`
> 
> However, is this project only compatible with Nvidia GPUs? Trying to launch the app afterwards threw the following error : `RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`
> 
> Indeed, I don't have a Nvidia GPU/drivers

yes it unfortunately is

**Comment by maksimus256** [comment]
> Try that : "pip uninstall torch torchvision torchaudio pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 " it worked for me

Thank you, it helped
